// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Balance API
 *
 * Derives addresses from an extended public key (XPUB) or equivalent, retrieves balances for a given cryptocurrency, and converts them to the requested fiat currency using an external rate service. 
 *
 * API version: 1.0.2
 */

package cryptobalancerest




type BalanceGet200Response struct {

	// Balance converted to the requested fiat currency.
	Value float64 `json:"value,omitempty"`

	// Balance in the requested cryptocurrency.
	Balance float64 `json:"balance,omitempty"`

	// Change in fiat value over the past 24 hours (positive = gain, negative = loss).
	Change24h float64 `json:"change24h,omitempty"`
}

// AssertBalanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertBalanceGet200ResponseRequired(obj BalanceGet200Response) error {
	return nil
}

// AssertBalanceGet200ResponseConstraints checks if the values respects the defined constraints
func AssertBalanceGet200ResponseConstraints(obj BalanceGet200Response) error {
	return nil
}
