// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Bitcoin Balance API
 *
 * Derives Taproot addresses from an XPUB, checks balances via Electrum, and converts to a fiat currency using an external crypto rate service. 
 *
 * API version: 1.0.0
 */

package cryptobalancerest




type BalanceGet200Response struct {

	// Balance converted to fiat.
	Value float64 `json:"value,omitempty"`

	// Balance in BTC.
	Balance float64 `json:"balance,omitempty"`
}

// AssertBalanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertBalanceGet200ResponseRequired(obj BalanceGet200Response) error {
	return nil
}

// AssertBalanceGet200ResponseConstraints checks if the values respects the defined constraints
func AssertBalanceGet200ResponseConstraints(obj BalanceGet200Response) error {
	return nil
}
