openapi: 3.0.3
info:
  title: Crypto Balance API
  version: 1.0.2
  # 1.0.2: Added change24h field, updated description for general cryptocurrency support
  # 1.0.1: Use doubles for fiat value and balance
  # 1.0.0: Initial contract
  description: |
    Derives addresses from an extended public key (XPUB) or equivalent,
    retrieves balances for a given cryptocurrency, and converts them to
    the requested fiat currency using an external rate service.

paths:
  /balance:
    get:
      summary: Get account balance in crypto and fiat
      description: |
        Retrieves the balance for an extended public key (XPUB or equivalent),
        calculates its value in the requested fiat currency, and returns
        the current balance along with the 24-hour change in fiat value.
      parameters:
        - in: query
          name: xpub
          schema:
            type: string
          required: true
          description: Extended public key to derive addresses from.
        - in: query
          name: currency
          schema:
            type: string
            example: BTC
          required: true
          description: Cryptocurrency symbol.
        - in: query
          name: fiat
          schema:
            type: string
            example: USD
          required: true
          description: Fiat currency symbol.
      responses:
        "200":
          description: Balance successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
                    format: double
                    description: Balance converted to the requested fiat currency.
                    example: 35000.25
                  balance:
                    type: number
                    format: double
                    description: Balance in the requested cryptocurrency.
                    example: 1.23456789
                  change24h:
                    type: number
                    format: double
                    description: Change in fiat value over the past 24 hours (positive = gain, negative = loss).
                    example: -250.75
        "400":
          description: Invalid request (bad XPUB or parameters)
        "500":
          description: Internal server error
