/* tslint:disable */
/* eslint-disable */
/**
 * Bitcoin Balance API
 * Derives Taproot addresses from an XPUB, checks balances via Electrum, and converts to a fiat currency using an external crypto rate service. 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BalanceGet200Response
 */
export interface BalanceGet200Response {
    /**
     * Balance converted to fiat.
     * @type {number}
     * @memberof BalanceGet200Response
     */
    value?: number;
    /**
     * Balance in BTC.
     * @type {number}
     * @memberof BalanceGet200Response
     */
    balance?: number;
}

/**
 * Check if a given object implements the BalanceGet200Response interface.
 */
export function instanceOfBalanceGet200Response(value: object): value is BalanceGet200Response {
    return true;
}

export function BalanceGet200ResponseFromJSON(json: any): BalanceGet200Response {
    return BalanceGet200ResponseFromJSONTyped(json, false);
}

export function BalanceGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'balance': json['balance'] == null ? undefined : json['balance'],
    };
}

export function BalanceGet200ResponseToJSON(json: any): BalanceGet200Response {
    return BalanceGet200ResponseToJSONTyped(json, false);
}

export function BalanceGet200ResponseToJSONTyped(value?: BalanceGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'balance': value['balance'],
    };
}

